export const GET_LANZADERA = "GET_LANZADERA";
export const GET_NAME_LANZADERA = "GET_NAME_LANZADERA";
export const GET_NO_TRIPULADA = "GET_NO_TRIPULADA";
export const GET_NAME_NO_TRIPULADA = "GET_NAME_NO_TRIPULADA";
export const GET__TRIPULADA = "GET__TRIPULADA";
export const GET_NAME__TRIPULADA = "GET_NAME__TRIPULADA";
